kind: pipeline
type: docker
name: Building

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/php-fpm
    tag: latest
    username: ch1ch1
    password:
      from_secret: dockerhub-password

- name: deliver
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookurl
