kind: pipeline
type: docker
name: Building..
node:
  drone: ch1


steps:
- name: building & pushing
  image: plugins/docker
  settings:
    repo: ch1ch1/php-fpm
    tag: [ "latest","7.4-prod" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
