---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

steps:
- name: build & push php7.3
  image: plugins/docker
  settings:
    repo: ch1ch1/php-fpm
    tags: [ "7.3-prod" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: build & push php7.4.13
  image: plugins/docker
  settings:
    repo: ch1ch1/php-fpm
    dockerfile: Dockerfile-php8
    tags: [ "latest","7.4.13-prod" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: notification
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success, failure ]
---
kind: signature
hmac: 65f1a64e558ec0f756a2dbfdae3d7aa8b66fddeb3172a6e9137bed29fc2de58f

...
