kind: pipeline
type: docker
name: Building..
node:
  drone: ch1


steps:
- name: building & pushing
  image: plugins/docker
  settings:
    repo: ch1ch1/php-fpm
    tag: [ "latest","7.3-prod" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: notification
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ build.status }}.",
       "priority": 4,
       "title": "Squid build"
      }
  when:
    status: [ success, failure ]
