---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi
steps:
  - name: build & push php8
    image: plugins/docker
    settings:
      repo: ch1ch1/php-fpm
      tags: [ "8.0.15-prod", "latest" ]
      username: ch1ch1
      password:
        from_secret: dockerhub_token
  - name: build & push php7
    image: plugins/docker
    settings:
      repo: ch1ch1/php-fpm
      tags: [ "7.4.27-prod" ]
      username: ch1ch1
      dockerfile: Dockerfilephp7
      password:
        from_secret: dockerhub_token
  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]

trigger:
  event:
    - push
---
kind: signature
hmac: 4dbd2bfd765f07e33ab412fe19221b4b783a37e466ce259e38dab014d54e5a9c

...
