---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: ch1ch1/php-fpm
    tags: [ "8.0-prod" ]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
- name: notification success
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/ok.webp) **{{ repo.owner }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ success ]
- name: notification failure
  image: plugins/webhook
  settings:
    urls:
     from_secret: webhookgotify
    content_type: application/json
    template: |
      {
        "extras": {
        "client::display": {
        "contentType": "text/markdown"
        }
      },
       "message": "![](https://ch1ch1.fr/img/nok.webp) **{{ repo.owner }}** as updated **{{ repo.name }}**, result: **{{ build.status }}**.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [ failure ]

trigger:
  event:
  - push

---
kind: signature
hmac: 4d627c9bc2dd763e9eb370d60393d6d5cd8b94bb52a6f3c46bd6de561e242717

...
