---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
steps:
  - name: build & push php8
    image: plugins/docker
    settings:
      repo: ch1ch1/php-fpm
      tags: [ "8.0.23", "latest" ]
      username: ch1ch1
      password:
        from_secret: dockerhub_token
  - name: build & push php7
    image: plugins/docker
    settings:
      repo: ch1ch1/php-fpm
      tags: [ "7.4.30-debian" ]
      username: ch1ch1
      dockerfile: Dockerfilephp7
      password:
        from_secret: dockerhub_token
  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]

trigger:
  event:
    - push
---
kind: signature
hmac: acbe895cf9ab0f40d87d5cc5606f6ac0cf71ec647a0ee8193c8fd083dbfef4d8

...
