---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1

steps:
  - name: lint
    image: osshelp/drone-linter
    failure: ignore
    settings:
      dockerfiles:
        - Dockerfile
      markdown_files:
        - README.md
  - name: build & push
    image: plugins/docker
    settings:
      repo: ch1ch1/php-fpm
      tags: [ "8.0.10-prod", "latest" ]
      username: ch1ch1
      password:
        from_secret: dockerhub_token
  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]

trigger:
  event:
    - push
---
kind: signature
hmac: 9f72e79f1992b434a15bc0be7cdba3c17cfbb0ad8716206f5f59e8fb9de2af87

...
