---
when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:5.0.0'
  - &platforms 'linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: ch1ch1
        password:
          from_secret: docker_token
  - &publish_repos 'ch1ch1/php-fpm'

steps:
  build-php-fpm:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, '8.1-fpm']
      logins: *publish_logins
      dry-run: true
    when:
      - event: [pull_request, push]