---
when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx'
  - &platforms 'linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: ch1ch1
        password:
          from_secret: docker_token
  - &publish_repos 'ch1ch1/php-fpm'

steps:
  build-php-fpm8.1:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile8.1
      platforms: *platforms
      tag: [8.1-fpm, latest-8.1-fpm]
      logins: *publish_logins
    when:
      - event: [pull_request, push]
  build-php-fpm8.2:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile8.2
      platforms: *platforms
      tag: [8.2-fpm, latest-8.2-fpm]
      logins: *publish_logins
    when:
      - event: [pull_request, push]
  build-php-fpm8.3:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile8.3
      platforms: *platforms
      tag: [8.3-fpm, latest-8.3-fpm]
      logins: *publish_logins
    when:
      - event: [pull_request, push]
  build-php-fpm8.4:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile8.4
      platforms: *platforms
      tag: [8.4-fpm, latest-8.4-fpm]
      logins: *publish_logins
    when:
      - event: [pull_request, push]